/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck

// ===============================================================
// This file is auto-generated by @tanstack/router-plugin.
// It will be regenerated on `pnpm dev` or `pnpm build`.
// The placeholder below exists so `tsc --noEmit` doesn't fail
// before Vite has run at least once.
// ===============================================================

import { createRootRoute } from "@tanstack/react-router";

const rootRoute = createRootRoute();
export const routeTree = rootRoute;

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {}
}
/* prettier-ignore-end */
